/* window.addEventListener("load", function () =>{ }) runs a function once the page loads. */

window.addEventListener("load", function () {
  /* 
   Everything inside this function will fire once the page loads.
   Our init() function is defined below and it's what sets the interactive part of the page in motion.  
   */
  init();
});


/* 
Setting the variables top_id and bottom_id as the ids of the divs we want to target later (this way we don't have to write it again and again if we need a reference to the ids later.
*/
const top_id = "first-half-target"; 
const bottom_id = "second-half-target";


/* The init() function defined here is where the real interaction happens. All of the active code is run here. */
const init = () => {

  /*
    document.getElementById allows to actually grab a reference to an element on the page. Here we grab a reference to our two top and bottom divs so that we can interact with them further. 
  */
  let top_div = document.getElementById(top_id);
  let bottom_div = document.getElementById(bottom_id);



  /* Now we USE the two references we have to our divs and replace their innerHTML (all the stuff contained within the div tag) with our story text.  */
  top_div.innerHTML = story_text;
  bottom_div.innerHTML = story_text;
};


/* Here we declare a variable story_text that holds the value of our text (now we don't have to copy and paste huge blocks of text into our markup*/
const story_text = `The universe (which others call the Library) is composed of an indefinite and perhaps infinite number of hexagonal galleries, with vast air shafts between, surrounded by very low railings. 
From any of the hexagons one can see, interminably, the upper and lower floors. The distribution of the galleries is invariable. Twenty shelves, five long shelves per side, cover all the sides except two; their height, which is the distance from floor to ceiling, scarcely exceeds that of a normal bookcase. One of the free sides leads to a narrow hallway which opens onto another gallery, identical to the first and to all the rest. To the left and right of the hallway there are two very small closets. In the first, one may sleep standing up; in the other, satisfy one's fecal necessities. Also through here passes a spiral stairway, which sinks abysmally and soars upwards to remote distances. In the hallway there is a mirror which faithfully duplicates all appearances. Men usually infer from this mirror that the Library is not infinite (if it were, why this illusory duplication?); I prefer to dream that its polished surfaces represent and promise the infinite... Light is provided by some spherical fruit which bear the name of lamps. There are two, transversally placed, in each hexagon. The light they emit is insufficient, incessant. Like all men of the Library, I have traveled in my youth; I have wandered in search of a book, perhaps the catalogue of catalogues; now that my eyes can hardly decipher what I write, I am preparing to die just a few leagues from the hexagon in which I was born. Once I am dead, there will be no lack of pious hands to throw me over the railing; my grave will be the fathomless air; my body will sink endlessly and decay and dissolve in the wind generated by the fall, which is infinite. I say that the Library is unending. The idealists argue that the hexagonal rooms are a necessary form of absolute space or, at least, of our intuition of space. They reason that a triangular or pentagonal room is inconceivable. (The mystics claim that their ecstasy reveals to them a circular chamber containing a great circular book, whose spine is continuous and which follows the complete circle of the walls; but their testimony is suspect; their words, obscure. This cyclical book is God.)`;
